name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
jobs:
  CI:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with: 
          file: ./
          context: .
          push: true
          tags: |
            otaviomartins/cadastro-alunos:latest
            otaviomartins/cadastro-alunos:${{github.run_number}}
